Update config.yml
- Add sccache on Linux and Windows.
- Unify all linting tasks into a single job.
- Rename `rust` build and test on Linux to
  match Windows job.
- Use `debian:buster-slim` as the base image
  on Linux.
- Bump docs deploy base image to LTS node.
- Split ruby/spec suite testing into its own job.
- Suppress errors in ruby/spec job.
- Use `shfmt` to discover sources for `shellcheck`.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,5 @@
 version: 2.1
 orbs:
-  shellcheck: circleci/shellcheck@1
   win: circleci/windows@2.1.0
 commands:
   rubocop:
@@ -11,111 +10,91 @@ commands:
     steps:
       - restore_cache:
           keys:
-            - ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
+            - v1-bundler-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
       - run:
           name: Bundle Install
-          working_directory: << parameters.target >>
-          command: bundle install --path "$HOME/vendor/$LOCKFILE_CHECKSUM"
-          environment:
-            LOCKFILE_CHECKSUM: "{{ checksum '<< parameters.target >>/Gemfile.lock' }}"
+          working_directory: "<< parameters.target >>"
+          command: |
+            bundle install --path ~/vendor
       - run:
           name: Lint Ruby With RuboCop
-          working_directory: << parameters.target >>
+          working_directory: "<< parameters.target >>"
           command: |
             bundle exec rubocop --version
             bundle exec rubocop
       - save_cache:
-          key: ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
+          key: v1-bundler-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
           paths:
-            - ~/vendor/{{ checksum "<< parameters.target >>/Gemfile.lock" }}
+            - "~/vendor"
 jobs:
-  rust:
+  artichoke-x86_64-linux:
     docker:
-      - image: circleci/rust:1.39.0-buster
+      - image: debian:buster-slim
     resource_class: large
     steps:
       - checkout
       - restore_cache:
-          key: rust-cargo-v4-{{ checksum "Cargo.lock" }}
+          name: Restore sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
       - run:
           name: Install Rust Toolchain
           command: |
-            rustup toolchain install "$(cat rust-toolchain)"
-            rustup component add rustfmt
-            rustup component add clippy
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --profile minimal --default-toolchain "$(cat rust-toolchain)"
+      - run:
+          name: Install Toolchain
+          working_directory: "~"
+          command: |
+            apt-get install -y clang bison
+            git clone https://github.com/rbenv/ruby-build.git
+            PREFIX=/usr/local ./ruby-build/install.sh
+            ruby-build "$(cat .ruby-version)" /usr/local
+      - run:
+          name: Install sccache
+          command: |
+            cargo install sccache
+            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
+            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
+      - run:
+          name: Installed Toolchain Versions
+          command: |
             rustc --version --verbose
             cargo --version --verbose
-            rustfmt --version
-            cargo clippy -- --version
-      - run:
-          # Debian Buster includes ruby 2.5
-          # FIXME: we should really be installing 2.6.3 since that is our stdlib dep.
-          name: Install MRI Ruby
-          command: |
-            sudo apt-get install -y ruby-full
             ruby --version
-      - run:
-          # https://github.com/mruby/mruby/blob/master/doc/guides/compile.md#prerequisites
-          name: Install mruby Build Dependencies
-          command: |
-            sudo apt-get install -y bison
-            bison --version
-      - run:
-          # needed for cc crate in build.rs
-          name: Install clang
-          command: |
-            sudo apt-get install -y clang
             clang --version
+            bison --version
       - run:
           name: Build workspace without default features
           command: |
             cargo build -p artichoke-backend --no-default-features
             touch artichoke-backend/build.rs
+          environment:
+            RUST_BACKTRACE: 1
       - run:
           name: Build Workspace
           command: |
             cargo build
+          environment:
+            RUST_BACKTRACE: 1
       - run:
           name: Test Workspace
           command: cargo test --all-features
           environment:
             RUST_BACKTRACE: 1
-      - run:
-          name: Format Rust Sources
-          command: |
-            rustfmt --version
-            cargo fmt -- --check --color=auto
-      - run:
-          name: Lint Rust With Clippy
-          command: |
-            cargo clippy -- --version
-            cargo clippy --all-targets --all-features
-      - run:
-          name: Check Docs
-          command: |
-            cargo doc --no-deps --all
-      - run:
-          name: ruby/spec Compliance Regression Test
-          command: |
-            ./scripts/spec-compliance.sh --artichoke
       - save_cache:
-          key: rust-cargo-v4-{{ checksum "Cargo.lock" }}
+          name: Save sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
           paths:
-            - "~/.cargo"
-            - "./target"
-      - persist_to_workspace:
-          root: target
-          paths:
-            - doc
+            - "~/.cache/sccache"
   artichoke-x86_64-windows:
     executor:
       name: win/default
     steps:
       - checkout
       - restore_cache:
-          key: rust-win-cargo-v1-{{ checksum "Cargo.lock" }}
+          name: Restore sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
       - run:
-          name: Install Rust Toolchain
+          name: Install Toolchain
           command: |
             # Install rustup
             $client = new-object System.Net.WebClient
@@ -125,20 +104,14 @@ jobs:
             # This is necessary because otherwise cargo fails when trying to use git?
             mkdir .cargo
             Add-Content .cargo\config "[net]`ngit-fetch-with-cli = true"
-      - run:
-          name: Install MRI Ruby
-          command: |
             choco install ruby --no-progress --version=2.6.3.1
-      - run:
-          # needed for cc crate in build.rs
-          name: Install clang
-          command: |
             choco install visualstudio2019-workload-vctools
             choco install llvm
-      - run:
-          name: Install bison
-          command: |
             choco install winflexbison3 --ignore-checksums
+      - run:
+          name: Install sccache
+          command: |
+            cargo install sccache
       - run:
           name: Installed Toolchain Versions
           command: |
@@ -153,6 +126,8 @@ jobs:
             cargo build
           environment:
             RUST_BACKTRACE: 1
+            RUSTC_WRAPPER: sccache
+            SCCACHE_CACHE_SIZE: 1G
             LIBCLANG_PATH: C:\Program Files\LLVM\bin
       - run:
           name: Test Workspace
@@ -161,84 +136,125 @@ jobs:
             % 'suppressing test failures. See GH-359.'
           environment:
             RUST_BACKTRACE: 1
+            RUSTC_WRAPPER: sccache
+            SCCACHE_CACHE_SIZE: 1G
             LIBCLANG_PATH: C:\Program Files\LLVM\bin
       - save_cache:
-          key: rust-win-cargo-v1-{{ checksum "Cargo.lock" }}
+          name: Save sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
           paths:
-            - C:\Users\cicleci\.cargo
-            - target
-  c:
+            - %LOCALAPPDATA%\Mozilla\sccache
+  artichoke-ruby/spec:
     docker:
-      - image: circleci/node:lts
+      - image: debian:buster-slim
+    resource_class: large
     steps:
       - checkout
       - restore_cache:
-          key: c-yarn-v2-{{ checksum "yarn.lock" }}
+          name: Restore sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
       - run:
-          name: Yarn Install
-          command: yarn install
+          name: Install Rust Toolchain
+          command: |
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --profile minimal --default-toolchain "$(cat rust-toolchain)"
+      - run:
+          name: Install Toolchain
+          working_directory: "~"
+          command: |
+            apt-get install -y clang bison
+            git clone https://github.com/rbenv/ruby-build.git
+            PREFIX=/usr/local ./ruby-build/install.sh
+            ruby-build "$(cat .ruby-version)" /usr/local
+      - run:
+          name: Install sccache
+          command: |
+            cargo install sccache
+            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
+            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
+      - run:
+          name: Installed Toolchain Versions
+          command: |
+            rustc --version --verbose
+            cargo --version --verbose
+            ruby --version
+            clang --version
+            bison --version
+      - run:
+          name: ruby/spec Compliance Regression Test
+          command: |
+            # Suppress failures from spec suite
+            ./scripts/spec-compliance.sh --artichoke || :
       - save_cache:
-          key: c-yarn-v2-{{ checksum "yarn.lock" }}
+          name: Save sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
           paths:
-            - ~/.cache/yarn
-            - node_modules
-      - run:
-          name: Format C Sources
-          command: ./scripts/format-c.sh --check
-  ruby:
+            - "~/.cache/sccache"
+  linter:
     docker:
-      - image: circleci/ruby:2.6.3
-    steps:
-      - checkout
-      - run:
-          name: Install bundler 2
-          command: sudo gem install bundler
-      - rubocop:
-          target: .
-  js:
-    docker:
-      - image: circleci/node:lts
+      - image: debian:buster-slim
     steps:
       - checkout
       - restore_cache:
-          key: js-yarn-v2-{{ checksum "yarn.lock" }}
-      - run: yarn install
-      - save_cache:
-          key: js-yarn-v2-{{ checksum "yarn.lock" }}
-          paths:
-            - ~/.cache/yarn
-            - node_modules
+          key: v1-node-modules-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
+      - restore_cache:
+          name: Restore sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
       - run:
-          name: yarn check
+          name: Install Rust Toolchain
           command: |
-            yarn check --integrity
-            yarn check --verify-tree
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y -q --profile minimal --default-toolchain "$(cat rust-toolchain)" --component rustfmt clippy
       - run:
-          name: Lint JavaScript with eslint
-          command: yarn run eslint --ext .html,.js .
-  shell-format:
-    docker:
-      - image: peterdavehello/shfmt:latest
-    steps:
-      - checkout
-      - run:
-          name: Format Shell Sources
+          name: Install Toolchain
+          working_directory: "~"
           command: |
+            git clone https://github.com/rbenv/ruby-build.git
+            PREFIX=/usr/local ./ruby-build/install.sh
+            ruby-build "$(cat .ruby-version)" /usr/local
+            gem install bundler
+            curl -sSfL https://deb.nodesource.com/setup_13.x | bash -
+            apt-get install -y nodejs
+            curl -sSf https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
+            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
+            apt-get update
+            apt-get install --no-install-recommends -y yarn
+            yarn install
+            curl -o- -sSfL https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz | tar x shellcheck-stable/shellcheck
+            mv shellcheck-stable/shellcheck /usr/local/bin
+            chmod +x /usr/local/bin/shellcheck
+            curl -o/usr/local/bin/shfmt -sSfL https://github.com/mvdan/sh/releases/download/v2.6.4/shfmt_v2.6.4_linux_amd64
+            chmod +x /usr/local/bin/shfmt
+      - run:
+          name: Install sccache
+          command: |
+            cargo install sccache
+            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
+            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
+      - run:
+          name: Installed Toolchain Versions
+          command: |
+            rustc --version --verbose
+            cargo --version --verbose
+            sccache --version
+            rustfmt --version
+            cargo clippy -- --version
+            ruby --version
+            node --version
+            yarn --version
+            yarn --silent clang-format --version
+            shellcheck --version
             shfmt -version
-            shfmt -f . | grep -v target/ | grep -v node_modules/ | grep -v vendor/ | xargs shfmt -i 2 -ci -s -w
-  text:
-    docker:
-      - image: circleci/node:lts
-    steps:
-      - checkout
-      - restore_cache:
-          key: text-yarn-v2-{{ checksum "yarn.lock" }}
-      - run: yarn install
-      - save_cache:
-          key: text-yarn-v2-{{ checksum "yarn.lock" }}
-          paths:
-            - ~/.cache/yarn
-            - node_modules
+      - run:
+          name: Format Rust Sources
+          command: |
+            cargo fmt -- --check --color=auto
+      - run:
+          name: Lint Rust With Clippy
+          command: |
+            cargo clippy --all-targets --all-features
+      - run:
+          name: Check Rust Docs
+          command: |
+            cargo doc --no-deps --all
       - run:
           name: Format Text Sources
           command: |
@@ -249,9 +265,46 @@ jobs:
             ./scripts/format-text.sh --check "yaml"
             ./scripts/format-text.sh --check "yml"
             ./scripts/format-text.sh --check "md"
+      - run:
+          name: Format Shell Sources
+          command: |
+            shfmt -f . | grep -v target/ | grep -v node_modules/ | grep -v vendor/ | xargs shfmt -i 2 -ci -s -d
+      - run:
+          name: Lint Shell Sources
+          command: |
+            shfmt -f . | grep -v target/ | grep -v node_modules/ | grep -v vendor/ | xargs shellcheck
+      - run:
+          name: Format C Sources
+          command: |
+            ./scripts/format-c.sh --check
+      - run:
+          name: yarn check
+          command: |
+            yarn check --integrity
+            yarn check --verify-tree
+      - run:
+          name: Lint JavaScript with eslint
+          command: |
+            yarn run eslint --ext .html,.js .
+      - rubocop:
+          target: .
+      - save_cache:
+          name: Save sccache cache
+          key: v1-sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
+          paths:
+            - "~/.cache/sccache"
+      - save_cache:
+          key: v1-node-modules-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
+          paths:
+            - "~/.cache/yarn"
+            - "node_modules"
+      - persist_to_workspace:
+          root: target
+          paths:
+            - "doc"
   gh-pages-deploy:
     docker:
-      - image: node:8.10.0
+      - image: node:lts
     steps:
       - checkout
       - add_ssh_keys:
@@ -260,15 +313,10 @@ jobs:
       - attach_workspace:
           at: target
       - restore_cache:
-          key: docs-yarn-v1-{{ checksum "yarn.lock" }}
+          key: v1-node-modules-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
       - run: yarn install
-      - save_cache:
-          key: docs-yarn-v1-{{ checksum "yarn.lock" }}
-          paths:
-            - ~/.cache/yarn
-            - node_modules
       - run:
-          name: Copy playground redirect
+          name: Copy doc asset overrides
           command: cp assets/* target/doc
       - run:
           name: Deploy docs to gh-pages branch
@@ -277,22 +325,22 @@ jobs:
               --user "ci-build <ci-build@hyperbo.la>" \
               --message "[skip ci] build docs" \
               --dist target/doc
+      - save_cache:
+          key: v1-node-modules-cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
+          paths:
+            - "~/.cache/yarn"
+            - "node_modules"
 workflows:
   version: 2
   build:
     jobs:
-      - rust
+      - artichoke-x86_64-linux
       - artichoke-x86_64-windows
-      - c
-      - ruby
-      - js
-      - shell-format
-      - shellcheck/check:
-          exclude: "*/vendor/*"
-      - text
+      - artichoke-ruby/spec
+      - linter
       - gh-pages-deploy:
           requires:
-            - rust
+            - linter
           filters:
             branches:
               only: master
